# Generated by Django 5.2.4 on 2025-07-11 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agronexus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='perfil',
        ),
    ]
