# Generated by Django 5.2.4 on 2025-07-11 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agronexus', '0002_migrate_perfil_to_groups'),
        ('agronexus', '0002_remove_perfil_field'),
    ]

    operations = [
    ]
