# Generated by Django 5.2.4 on 2025-07-13 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agronexus', '0004_add_especies_racas'),
    ]

    operations = [
        migrations.AddField(
            model_name='parto',
            name='filhotes',
            field=models.ManyToManyField(blank=True, related_name='parto_origem', to='agronexus.animal'),
        ),
        migrations.AddField(
            model_name='parto',
            name='numero_filhotes',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='animal',
            name='categoria',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='animal',
            name='especie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animais', to='agronexus.especieanimal'),
        ),
        migrations.AlterField(
            model_name='parto',
            name='bezerro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parto_origem_unico', to='agronexus.animal'),
        ),
    ]
