# Generated by Django 5.2.4 on 2025-07-13 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agronexus', '0005_remove_default_especie'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='aptidao',
            field=models.CharField(blank=True, choices=[('corte', 'Corte'), ('leite', 'Leite'), ('dupla_aptidao', 'Dupla Aptidão')], help_text='Aptidão predominante do lote', max_length=20),
        ),
        migrations.AddField(
            model_name='lote',
            name='finalidade',
            field=models.CharField(blank=True, choices=[('cria', 'Cria'), ('recria', 'Recria'), ('engorda', 'Engorda')], help_text='Finalidade do lote na propriedade', max_length=20),
        ),
        migrations.AddField(
            model_name='lote',
            name='sistema_criacao',
            field=models.CharField(blank=True, choices=[('intensivo', 'Intensivo'), ('extensivo', 'Extensivo'), ('semi_extensivo', 'Semi-Extensivo')], help_text='Sistema de criação utilizado para o lote', max_length=20),
        ),
    ]
