# Generated by Django 5.2.4 on 2025-07-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agronexus', '0006_lote_aptidao_lote_finalidade_lote_sistema_criacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='criterio_agrupamento',
            field=models.CharField(blank=True, help_text='Ex: Bezerros desmamados em 2025', max_length=200),
        ),
    ]
