# Generated by Django 5.2.4 on 2025-08-04 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agronexus', '0007_alter_lote_criterio_agrupamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propriedade',
            name='cnpj_cpf',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='propriedade',
            name='inscricao_estadual',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
