# Generated by Django 5.2.4 on 2025-08-05 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agronexus', '0008_alter_propriedade_cnpj_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='categoria',
            field=models.CharField(choices=[('bezerro', 'Bezerro'), ('bezerra', 'Bezerra'), ('novilho', 'Novilho'), ('novilha', 'Novilha'), ('touro', 'Touro'), ('vaca', 'Vaca')], max_length=20),
        ),
        migrations.AlterField(
            model_name='animal',
            name='destino',
            field=models.CharField(blank=True, choices=[('venda_mercado', 'Venda para Mercado'), ('venda_leilao', 'Venda em Leilão'), ('abate', 'Abate'), ('doacao', 'Doação'), ('outro', 'Outro')], max_length=200),
        ),
        migrations.AlterField(
            model_name='animal',
            name='origem',
            field=models.CharField(blank=True, choices=[('proprio', 'Proprio'), ('compra', 'Compra'), ('leilao', 'Leilão'), ('doacao', 'Doação'), ('parceria', 'Parceria')], max_length=200),
        ),
    ]
