# Generated by Django 5.2.4 on 2025-08-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agronexus', '0009_alter_animal_categoria_alter_animal_destino_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='categoria',
            field=models.CharField(choices=[('bezerro', 'Bezerro'), ('bezerra', 'Bezerra'), ('novilho', 'Novilho'), ('novilha', 'Novilha'), ('touro', 'Touro'), ('vaca', 'Vaca'), ('cabrito', 'Cabrito'), ('cabrita', 'Cabrita'), ('bode_jovem', 'Bode Jovem'), ('cabra_jovem', 'Cabra Jovem'), ('bode', 'Bode'), ('cabra', 'Cabra'), ('cordeiro', 'Cordeiro'), ('cordeira', 'Cordeira'), ('carneiro_jovem', 'Carneiro Jovem'), ('ovelha_jovem', 'Ovelha Jovem'), ('carneiro', 'Carneiro'), ('ovelha', 'Ovelha'), ('cavalo', 'Cavalo'), ('egua', 'Égua'), ('potro', 'Potro'), ('porco', 'Porco'), ('leitao', 'Leitão')], max_length=20),
        ),
    ]
